### PR TITLE
Fix link problem by providing missing default impl for CallOpInterface

### PR DESCRIPTION
**Pull request by tyb0807**
This fixes
```
ld: warning: ignoring duplicate libraries: '-lc++'
Undefined symbols for architecture arm64:
  "mlir::enzymexla::KernelCallOp::getArgAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::getArgAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::getResAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::getResAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::setArgAttrsAttr(mlir::ArrayAttr)", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::setArgAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::ArrayAttr) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::setResAttrsAttr(mlir::ArrayAttr)", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::setResAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::ArrayAttr) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::removeArgAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::removeArgAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::removeResAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::removeResAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::getArgOperandsMutable()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::getArgOperandsMutable(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::KernelCallOp::setCalleeFromCallable(mlir::CallInterfaceCallable)", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::KernelCallOp>::setCalleeFromCallable(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::CallInterfaceCallable) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::getArgAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::getArgAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::getResAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::getResAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::setArgAttrsAttr(mlir::ArrayAttr)", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::setArgAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::ArrayAttr) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::setResAttrsAttr(mlir::ArrayAttr)", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::setResAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::ArrayAttr) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::removeArgAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::removeArgAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::removeResAttrsAttr()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::removeResAttrsAttr(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::getArgOperandsMutable()", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::getArgOperandsMutable(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*) in libXLADerivatives.a[2](Dialect.o)
  "mlir::enzymexla::JITCallOp::setCalleeFromCallable(mlir::CallInterfaceCallable)", referenced from:
      mlir::detail::CallOpInterfaceInterfaceTraits::Model<mlir::enzymexla::JITCallOp>::setCalleeFromCallable(mlir::detail::CallOpInterfaceInterfaceTraits::Concept const*, mlir::Operation*, mlir::CallInterfaceCallable) in libXLADerivatives.a[2](Dialect.o)
ld: symbol(s) not found for architecture arm64
```
introduced after https://github.com/EnzymeAD/Enzyme-JAX/commit/cb17aacb16a04fdf80729c5664f79908a5276456

I didn't try to come up with a cleaner solution, so please share your thoughts!

### CODE REVIEW

**Comment by chelini** [comment]
Thanks for the fix @tyb0807 there is already a PR https://github.com/EnzymeAD/Enzyme-JAX/pull/332#event-16249818643.
